apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    env: prod
    app: main
    tier: FE
    owner: Bagrat_Mukaelyan
spec:
  containers:
    - name: container-web
      image: mginx:latest
      ports:
        - containerPort: 80
    - name: container-api
      image: tomcat:latest
      ports:
        - containerPort: 80
